'Rh 50uM-tube':
  folder: 'C:/Users/larue/Chapman University/LaRue CatLab - Data/2024/2024.01.23/Rh 50uM-tube'
  range: [540,700]
  Models:
    Peak1:
      assignment: 'Peak 1'
      model: 'Gaussian'
      amplitude: {value: 0, min: 0, vary: True}
      center: {value: 600, min: 540, vary: True}
      sigma: {value: 20, vary: True}